export const RECEIVE_CITIES = 'RECEIVE_CITIES'
export const RECEIVE_STATIONS = 'RECEIVE_STATIONS'
export const SET_CITY = 'SET_CITY'
export const SET_MAP = 'SET_MAP'
export const SET_ZOOM = 'SET_ZOOM'