service: locomotion-etl
app: locomotion
org: adamjreed
custom:
  stage: ${opt:stage,'dev'}
  pythonRequirements:
    dockerizePip: non-linux
  config: ${file(./config/${self:provider.stage}.json)}
  secrets: ${ssm:/aws/reference/secretsmanager/${self:custom.config.secretsKey}~true}
provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.stage}
  iamRoleStatements:
    - Effect: Allow
      Action: s3:*
      Resource: arn:aws:s3:::${self:custom.config.bucket_name}*
    - Effect: Allow
      Action:
        - glue:*
      Resource: "*"
functions:
  fetchChicagoGTFS:
    handler: src/gtfs.handler
    timeout: 900
    environment: 
      BUCKET_NAME: ${self:custom.config.bucket_name}
      BUCKET_PREFIX: chicago/
      FEED_URL: ${self:custom.config.cities.chicago.feed_url}